// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/home/hanxiang/Cultivation/xiaowa/dumiUI-demo/node_modules/dumi/theme-default/slots/Toc/index.js';
